### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by omaresl** [diegomore97/DINO_GOOGLE_SMART#1]
No documentation under configuration management.

Add at least the next documentation:
- SDD (State Machine Design)
- Link to Change Management Tool
- Test Specification
- Test Report (On Realease)
- SW/HW Specifications

**Comment by diegomore97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agregar Documentación a Github](https://trello.com/c/SmsBXZRP/9-agregar-documentaci%C3%B3n-a-github)
