### ISSUE TITLE
Finger Use

### ISSUE THREAD

**Issue by omaresl** [diegomore97/DINO_GOOGLE_SMART#2]
A finger is not part of the system.

The microcontroller shall regulate the torque of the motor to avoid damage or undesired movements

**Comment by diegomore97** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bajar el angulo de movimiento del servomotor para no utilizar el dedo para fijar el servomotor](https://trello.com/c/xBrHLvAJ/10-bajar-el-angulo-de-movimiento-del-servomotor-para-no-utilizar-el-dedo-para-fijar-el-servomotor)
